framework:
    secret: '%env(APP_SECRET)%'
    session:
        handler_id: null
        save_path: '%kernel.cache_dir%/sessions'
        cookie_secure: true
        cookie_samesite: none
    trusted_proxies: '127.0.0.1,REMOTE_ADDR'
    trusted_headers:
        - 'x-forwarded-for'
        - 'x-forwarded-host'
        - 'x-forwarded-port'
        - 'x-forwarded-proto'
        - 'x-forwarded-prefix'
